@startsalt
!theme materia
{
  "새 할 일 추가"
  {
    "제목"
    {
      [                        ]
    }
    "내용 (선택 사항)"
    {
      [""]
      [""]
      [""]
    }
    "분류"
    {
      ( ) "대기 목록" (X) "기한 있는 일" ( ) "언젠가 할 일" ( ) "반복하는 일"
    }
    "기한 설정"
    {
      "날짜:" [          ] "시간:" [      ]
    }
    "반복 설정"
    {
      "주기:" ( ) "매일" ( ) "매주" ( ) "매월" "   " "요일/날짜:" [        ]
    }
    "---"
    {
      " {button:저장} " | " {button:취소} "
    }
  }
}
@endsalt
